### ISSUE TITLE
Errors on npm run build in django docker container

### ISSUE THREAD

**Issue by ramojo** [HyphaApp/hypha#2858]
**Describe the bug**

When I run docker-compose up, I get undefined variable errors and undefined mixin errors

**To Reproduce**

1. Go to '/root_of_application/docker'
2. Type 'docker-compose up' or 'docker compose up' depending on the version you use 
3. See error

**Expected behavior**

A successful, error free build
**Priority**

- High (keeping you from completing day-to-day tasks)

**Screenshots**
![image](https://user-images.githubusercontent.com/9459879/169835632-2e5d3ec9-afa1-45a9-997c-6a0668fc7521.png)

![image](https://user-images.githubusercontent.com/9459879/169836141-c24e8bc2-b4a4-4a2f-b003-9dab4833fcc6.png)

**Desktop (please complete the following information):**

 - OS: [Ubuntu 20.04.4 LTS]

**Comment by frjo** [comment]
A bug in the docker setup. I think I have fixed it now if you pull in latest main and see the just updated docs. It was working for other devs since we already have the node packages installed.

You need to run the docker build command from hypha root like this:

`docker-compose --file docker/docker-compose.yaml build`

The other docker commands can be run from the docker dir.

You might need to run build with the no cache flag to reset everything.

`docker-compose --file docker/docker-compose.yaml build --no-cache`

Please let me know if it works.

**Comment by ramojo** [comment]
/thanks for the quick reply. Unfortunately that didn't fix it. It did point me in the kind of direction I should be looking at though

**Comment by ramojo** [comment]
The problem was mainly sass-loader, webpack and webpack-cli refusing to update to the newer versions. Got into the container and upgraded them with yarn and those main errors went away. Left with just these 5

![image](https://user-images.githubusercontent.com/9459879/169904629-7057f106-d8c3-4028-93fb-08a0f43b26dc.png)

**Comment by frjo** [comment]
I merged in a new PR with a second attempt at fixing this. As you notice the docker stuff is little used, all the current devs prefer to run dev environments on metal.

This issue had not been noticed before since everyone testing already had a local "node_modules". 

I have now moved the `npm install` command to the entry point script so it is run after the code base have been mounted in the docker container.

The `docker-compose up` command will now create a "node_modules" dir in the code base if it does exist already.

To reset everything use:

`docker-compose --file docker/docker-compose.yaml build --no-cache`

Please try it out and report back.

**Comment by ramojo** [comment]
This works thanks. Had to go into the container again and pip install --upgrade django-bleach (to django-bleach-3.0.0) because I was getting errors: 
![image](https://user-images.githubusercontent.com/9459879/170865962-0e813221-aa0b-4f18-8b58-252824397b04.png)

Upgrading django-bleach fixes it

**Comment by ramojo** [comment]
This works thanks. I had to go into the container again and pip install --upgrade django-bleach (to django-bleach-3.0.0) because I was getting errors: 
![image](https://user-images.githubusercontent.com/9459879/170865962-0e813221-aa0b-4f18-8b58-252824397b04.png)

Upgrading django-bleach fixes it.

**Comment by frjo** [comment]
That should not be needed. We are running this code on many dev/test/live environments without issue.

`pip install -r requirements-dev.txt`

Should take care of everything. Maybe you updated the code and did not run the above command?

**Comment by ramojo** [comment]
I did and it installs django-bleach 1.0.0 which produces the above error. Let me also run it purely on metal and see if I encounter the same issues

**Comment by frjo** [comment]
Yes, the command will install everything specified in the requirements files. django-bleach==1.0.0 together with bleach==4.1.0 should not produce this error.
